# Site settings
title: Recipes
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Server
baseurl: "/recipes"
destination: _site
host: 0.0.0.0
port: 4001
url: http://turretcss.com
encoding: UTF-8
exclude: []

# URLs
permalink: /:categories/:title/

# Build settings
markdown: kramdown

# Repo
repo: https://github.com/scottdejonge/recipes